### ISSUE TITLE
Host names with dash (-) fail to parse.

### ISSUE THREAD

**Issue by Graymc** [jrop/tns#2]
Entries in the tnsnames file that contain dashes in the host name will cause a parsing error.  Example:

``
ABCD=
  (DESCRIPTION =
    (ADDRESS_LIST =
      (ADDRESS = (PROTOCOL = TCP)(HOST = rac-scan.dbs.myorg.com)(PORT = 1521))
    )
    (CONNECT_DATA =
      (SERVICE_NAME = ABCD)
    )
  )
``
Adding the dash character to the WORD regex handles the issue.

``.token('WORD', /[a-z0-9\._\-]+/i)``

**Comment by jrop** [comment]
@Graymc Thank you for reporting this!  Can you install v0.2.0 and try again?

**Comment by Graymc** [comment]
Tested 0.2.0.  Works find and handles the dashes in the names.  Thanks!
